name: Main CI/CD Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  # 1. Call the Gitleaks workflow
  run-gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  # 2. Call the SonarQube workflow
  run-sonarqube:
    uses: ./.github/workflows/sonarq.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # 3. Call the Trivy workflow
  run-trivy:
    uses: ./.github/workflows/trivy.yml

  # 4. Handle Slack Notifications for Success AND Failure
  notify-slack:
    needs: [run-sonarqube, run-gitleaks, run-trivy] 
    
    # 'always()' ensures this job runs even if Gitleaks, SonarQube, or Trivy fail
    if: always() 
    uses: ./.github/workflows/notify_slack.yml
    with:
      gitleaks_result: ${{ needs.run-gitleaks.result }}
      sonarqube_result: ${{ needs.run-sonarqube.result }}
      trivy_result: ${{ needs.run-trivy.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      