name: Main CI/CD Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  run-sonarqube:
    uses: ./.github/workflows/sonarq.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-sbom-sca:
    uses: ./.github/workflows/sbom_sca.yml

  notify-slack:
    needs: [run-sonarqube, run-gitleaks, run-sbom-sca]
    if: always()
    uses: ./.github/workflows/notify_slack.yml
    with:
      gitleaks_result: ${{ needs.run-gitleaks.result }}
      sonarqube_result: ${{ needs.run-sonarqube.result }}
      sbom_sca_result: ${{ needs.run-sbom-sca.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}